name: penalty_game
description: Penalty kick game built with Flame for Flutter Web.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  flutter_fortune_wheel: ^1.3.2
  go_router: ^14.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/penalty_game/
    - assets/images/wheel_game/
    - assets/images/guest_web/
    - assets/images/bingo_game/
    - assets/images/school/
    - assets/wheel_prizes.json
    - assets/guests.json
    - assets/schools.json
