name: penalty_game
description: Penalty kick game built with Flame for Flutter Web.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
